from typing import Protocol

from app.models import ApprovalRequest, Property, TaskLog, TaskRun


class Repository(Protocol):
    def initialize(self) -> None: ...
    def seed_properties(self, properties: list[Property]) -> None: ...
    def list_properties(self) -> list[Property]: ...
    def save_task(self, task: TaskRun) -> None: ...
    def get_task(self, task_id: str) -> TaskRun | None: ...
    def list_tasks(self) -> list[TaskRun]: ...
    def add_log(self, log: TaskLog) -> None: ...
    def list_logs(self, task_id: str) -> list[TaskLog]: ...
    def save_approval(self, approval: ApprovalRequest) -> None: ...
    def decide_approval(self, task_id: str, decision: str) -> ApprovalRequest | None: ...

